function xk1=jacobiIteration(D,R,f,xk,w)

%FUNKCJA WYKONUJACA JEDNA ITERACJE METODY JACOBIEGO
%A - MACIERZ UKLADU
%f - WEKTOR PRAWYCH STRON
%xk - PRZYBLIZENIE K
%w - WSPOLCZYNNIK PODRELAKSACJI
%xk1 - PRZYBLIZENIE K+1

%WYKONAJ ITERACJE
xk1=w*(D\(f-R*xk))+(1-w)*xk;